services:
  rvx-builder:
    container_name: rvx-builder
    restart: unless-stopped
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ./revanced/:/app/rvx-builder/revanced/
    ports:
      - 8000:8000
    environment:
      # Specific the port to open server
      # PORT: 8080
      # Specific settings.json and options.json path
      # SETTINGS_PATH: /app/rvx-builder/revanced/settings.json
      # OPTIONS_PATH: /app/rvx-builder/revanced/options.json
